### ISSUE TITLE
[PRE REVIEW]: WI Fast Stats: a collection of web apps for the visualization and analysis of WI Fast Plants data

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#103]
**Submitting author:** @crsl4 (<a href="http://orcid.org/0000-0002-9789-8915">Claudia Solis-Lemus</a>)
**Repository:** <a href="https://github.com/crsl4/fast-stats" target ="_blank">https://github.com/crsl4/fast-stats</a>
**Version:** v2.0
**Editor:** @JasonJWilliamsNY
**Reviewers:** pierrerogy, magitz

**Author instructions**

Thanks for submitting your paper to JOSE @crsl4. **Currently, there isn't an JOSE editor assigned** to your paper.

@crsl4 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.30 s (118.7 files/s, 58528.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
CSS                              6            884            112           6968
R                                4            419            508           2124
JavaScript                      12            474            490           2052
HTML                             3            242            286           1371
SVG                              1              0              0            504
Markdown                         6            151              0            399
Rmd                              2            130            218            353
TeX                              1              3              0             34
YAML                             1              1              4             18
-------------------------------------------------------------------------------
SUM:                            36           2304           1618          13823
-------------------------------------------------------------------------------


Statistical information for the repository '2bc8d4a04dd3f55c2282c5a3' was
gathered on 2021/02/18.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Yizhou Liu                       1          3016              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Yizhou Liu                 3016          100.0          0.0               16.31
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1126/science.232.4756.1385 may be a valid DOI for title: Rapid-cycling populations of Brassica

INVALID DOIs

- https://doi.org/10.1002/lol2.10165 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment]
PDF failed to compile for issue #103 with the following error: 

 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.290 ....edu}{\nolinkurl{solislemus@wisc.edu}})}}

Looks like we failed to compile the PDF

**Comment by labarba** [comment]
hi there! 👋 

We've been slow here, due to unmanageable work loads that trump volunteer tasks. Thanks for your patience. I note that your paper did not compile, but inspected the [markdown file for the article](https://github.com/crsl4/fast-stats/blob/master/ms/paper.md). It is not clear how this work fits in the scope of JOSE, as this seems to be a pure web app? 

JOSE aims to publish computational learning modules, where computing (coding) is used in a context of learning another subject. We extend the scope to allow for software infrastructure in support of computational learning, e.g., auto-graders of student-submitted code. But we did not target JOSE for web apps that learners interact with as a GUI. If you wanted your submission considered regardless of this, you would make your case in the paper. See the section on our documentation about [what the paper should contain](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain).

**Comment by crsl4** [comment]
Thanks @labarba ! I completely understand the reviewing speed. 

We originally submitted the paper to JOSS because this is an open-source bioinformatics tool (collection of web apps) that students and researchers can use for data visualization and data analysis on plant experimental data that is very widely used across the US ([WI Fast Plants](https://fastplants.org/)). For example, experiments with WI Fast Plants have been run by K-16 teachers around the world for nearly 30 years as an educational model-organism, so we have 30 years of collected data with no tools to visualize/analyze! We produced this suite as a data science tool to researchers/students doing research on WI Fast Plants so that 1) they have tools to visualize/analyze, 2) they can explore how the web apps are created by browsing the code. Existing data science tools are proprietary, so they are just a black box!

Anyway, personally I think that it fits well with JOSS given that it is an open-source bioinformatics tool, but given that our audience are K-16 teachers and students doing research, the editors at JOSS suggested that we submit to JOSE.

So, I am not sure what is the best course of action! 
Back to the JOSE scope, we are providing a software infrastructure in support of learning, but the learning is on the plants based on collected data from experiments, we are just providing the bioinformatics tool.

Let me know what you think, thanks!

**Comment by crsl4** [comment]
@yizhou0522 tagging the first author

**Comment by labarba** [comment]
I see. Thanks for the clarification. Internally, JOSE editors have been doing some soul-searching on our scope for web applications, but we have published tools of that category. I understand that JOSS would not consider it, not being research software per se. 

Question: are data sets also open? That is, would a reviewer be able to test the apps with real data that you provide?

**Comment by crsl4** [comment]
Yes! There are open data in the web apps.
The goal for the web apps is that people will collect their own data from the plant experiments and then use the web app to analyze it.
But the web apps have built in sample data that anyone can use to learn about the plant experiments without having to do the plant experiments themselves. 
Using the test data is as simple as clicking the "sample data" option in the Data Upload section.
Currently, the web apps will be used in the Intro Biology class at our university (with 1400 students) who will conduct research experiments with fast plants and use the app to analyze the collected data. We think it is a very useful software, but at the same time, we completely understand if it does not fall within the scope of JOSE (even after the soul-searching ;) )

**Comment by crsl4** [comment]
Hello @labarba , 
No pressure at all, but just wondering if you have any updates on the JOSE scope and the suitability of our work.
Again, just touching base and as a fellow reviewer/editor, I completely understand the speed of review these days :)

**Comment by labarba** [comment]
@whedon query scope

**Comment by whedon** [comment]
Submission flagged for editorial review.

**Comment by labarba** [comment]
@whedon invite @JasonJWilliamsNY as editor

**Comment by whedon** [comment]
@JasonJWilliamsNY has been invited to edit this submission.

**Comment by JasonJWilliamsNY** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #103 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.290 ....edu}{\nolinkurl{solislemus@wisc.edu}})}}

Looks like we failed to compile the PDF

```

**Comment by crsl4** [comment]
I had this error too, but it does compile locally per the instructions. Not sure what the error is about!

**Comment by JasonJWilliamsNY** [comment]
I'll comment to ask @labarba to help us out... I do have emails out to potential reviewers so stay tuned!

**Comment by labarba** [comment]
@openjournals/dev Can you help us with a paper that doesn't compile?

**Comment by crsl4** [comment]
Thanks Jason!

**Comment by JasonJWilliamsNY** [comment]
@crsl4 A few more invitations to review have gone out. @labarba did @openjournals/dev follow up on the help request?

**Comment by crsl4** [comment]
Great, thanks for keeping me posted, Jason!

**Comment by xuanxu** [comment]
The PDF is not compiling due to an unscaped character. [This change](https://github.com/crsl4/fast-stats/pull/51) should fix it.

**Comment by JasonJWilliamsNY** [comment]
> The PDF is not compiling due to an unscaped character. [This change](https://github.com/crsl4/fast-stats/pull/51) should fix it.

Thanks @xuanxu @crsl4 can you accept the change

**Comment by JasonJWilliamsNY** [comment]
@whedon add pierrerogy as reviewer

**Comment by whedon** [comment]
OK, pierrerogy is now a reviewer

**Comment by crsl4** [comment]
Yes, I had merged the change already, thanks for catching that!

**Comment by JasonJWilliamsNY** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00103/jose.00103/10.21105.jose.00103.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00103/jose.00103/10.21105.jose.00103.pdf) :page_facing_up: :point_left:

**Comment by crsl4** [comment]
Great! I will review the proofs, thanks!

**Comment by JasonJWilliamsNY** [comment]
Emails to additional reviewer is out so still working on this to at least assign before holiday breaks

**Comment by JasonJWilliamsNY** [comment]
Talking with additional potentials reviewers so just posting an update

**Comment by JasonJWilliamsNY** [comment]
More invitations out - this is Niche but I won't give up!

**Comment by whedon** [comment]
Here's the current list of reviewers: https://bit.ly/jose-reviewers

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/159.
