### ISSUE TITLE
[PRE REVIEW]: A short course about fitting models with the `scipy.optimize` module

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#11]
**Submitting author:** @arokem (<a href="http://orcid.org/0000-0003-0679-1985">Ariel Rokem</a>)
**Repository:** <a href="https://github.com/arokem/scipy-optimize" target ="_blank">https://github.com/arokem/scipy-optimize</a>
**Version:** 0.1
**Editor:** @labarba
**Reviewers:** @oliviaguest, @ThomasA

**Author instructions**

Thanks for submitting your paper to JOSE @arokem. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@arokem if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00011/jose.00011/10.21105.jose.00011.pdf)

**Comment by arokem** [comment]
@whedon commands

**Comment by arokem** [comment]
From a quick read of their reviewing interests, I'd suggest Lindsey Heagy, Sidafa Conde, Thomas Arlidsen, and/or Manjari Narayan as reviewers.

Sadly, the google sheet of potential reviewers doesn't have their Github users, so I couldn't tag them here, see https://github.com/openjournals/jose/issues/12

**Comment by labarba** [comment]
Hang on, @arokem — we had a telecon with the editorial board last week, and have some more precise guidance on what we want in the paper. Stay tuned!

**Comment by arokem** [comment]
OK. Will sit tight.

**Comment by arokem** [comment]
Will do.

Thanks for the guidance!

**Comment by arokem** [comment]
I believe that changes implemented in https://github.com/arokem/scipy-optimize/commit/3f0810b74f5446f7a242fc793dcafa5b54514b90 should cover these requirements.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00011/jose.00011/10.21105.jose.00011.pdf)

**Comment by labarba** [comment]
@whedon assign @labarba as editor

**Comment by whedon** [comment]
OK, the editor is @labarba

**Comment by labarba** [comment]
@arokem — I'm looking for reviewer(s) for your submission now. In the meantime, I have the following direction for you:

- Move "contributing" and "reporting issues" out of the paper and into a README in your repo.
- Let's re-organize the structure of the paper a little bit. For your fist paragraph, use the heading "Summary," instead of "Description." Then you have "Statement of Need" and "Learning Objectives," which are fine. Then, you could have a top heading "Description of the module," under which "Usage" can be a sub-heading, but put that after other sub-heading content (next item).
- The long heading "Content, instructional design, and experience of use in teaching and learning situations" is a little ugly; this comes straight from the Author Guide, I realize, but we didn't mean for it to be a heading, just direction on what to include. Yet, the content under this heading is scant. So, reorganize this under the heading "Description of the module," and tell us the story of this tutorial.

> This tutorial began as a blog post blah-blah Software Carptentry [link]. It was taught as a synchronous online workshop as part of the series blah-blah UC Davis [link]. The example data in the tutorial comes from an experiment in visual neuroscience [reference]. Learners follow along as we read the data from a comma-separated file, plot the data, then transform the data to increasingly reveal its structure. Then follows a lesson on different kinds of models blah-blah linear/nonlinear. We define the functional form for our model [reference] and a measure of modeling error. Blah-blah optimize. Blah evaluate. Poof, done.

Get my drift? Walk us through the tutorial in one brief paragraph, so we imagine what it is to sit through it.

If you have anything to add about _why_ you broke things down like you did, please tell us. This is the "instructional design" question. Is there a concept that learners find particularly difficult here, and you spend more time on it? And so on.

**Comment by labarba** [comment]
The [Author Guide](http://jose.theoj.org/about#author_guidelines) says:

> Computational learning modules should be complete and immediately usable for self-learning or adoption by other instructors. 

Essentially, what we want the JOSE paper to do is to show that the submission meets the eligibility requirement. So it should explain how an instructor other than the author might adopt the module, or how an independent learner might use it.

**Comment by arokem** [comment]
Thanks for the comments @labarba!

Changes implemented in
https://github.com/arokem/scipy-optimize/commit/38c1d52b2fe7605f93e1a4dd45d09a05275b759b
and
https://github.com/arokem/scipy-optimize/commit/dbc794b8522261d29259100992b29495b3a73212

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00011/jose.00011/10.21105.jose.00011.pdf)

**Comment by labarba** [comment]
@whedon assign @oliviaguest as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @oliviaguest

**Comment by labarba** [comment]
@whedon add @ThomasA as reviewer

**Comment by whedon** [comment]
OK, @ThomasA is now a reviewer

**Comment by labarba** [comment]
@whedon start review magic-word=bananas

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/16. Feel free to close this issue now!
