### ISSUE TITLE
[PRE REVIEW]: Org-Coursepack

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#24]
**Submitting author:** @joonro (<a href="http://orcid.org/0000-0002-5895-163X">Joon Ro</a>)
**Repository:** <a href="https://github.com/joonro/Org-Coursepack" target ="_blank">https://github.com/joonro/Org-Coursepack</a>
**Version:** v1.0.1
**Editor:** @csev
**Reviewers:** @pschloss, @gregcaporaso

**Author instructions**

Thanks for submitting your paper to JOSE @joonro. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@joonro if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks. @csev it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00024/jose.00024/10.21105.jose.00024.pdf)

**Comment by labarba** [comment]
👋  @csev  — The submitting author suggested you as editor. Since this will be your first editing assignment, let me know if you need to bounce ideas about selecting reviewers. Check out the [Editor's Guide](https://github.com/labarba/jose/blob/master/EditorsGuide.md) I put together, if you haven't. It describes the editor workflow, including needed `@whedon` commands.

**Comment by joonro** [comment]
Reviewer suggestion: I think Stefania Druga (@stefania11) would be a suitable reviewer for this submission. Thank you very much.

**Comment by csev** [comment]
Hey @joonro - sorry for the delay.  Thanks for your submission. I like the paper and topic a lot.   I think we need to explore new ways or authoring, reusing, and remixing each other's content - and in particular doing so though github.  A couple of quick questions.  (1) There is a ?? in the paper - does that need to be resolved?  (2) looking at both the paper and your Repo, I was hoping to find a link to an example web site / course that uses this approach, and (3) if you have an example of any kind of remix / reuse of course materials I think that it would be s nice addition.  I understand that even if we prepare for (3) it does not always happen - I just thought I would ask.

**Comment by joonro** [comment]
Dear @csev - thank you so much for the comments and sorry for the late reply. I have been away for a conference and just got back. I will respond to your comments soon!

**Comment by joonro** [comment]
@csev, Regarding your question (1), I just fixed the citation with joonro/Org-Coursepack@d667599e137a044d182c7656cd5895bb098bfbb0 - I removed underscores in the BibTeX Key. I'm not sure how to update the compiled pdf file so I cannot verify that the issue is fixed at the moment, but I hope this was the issue.

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00024/jose.00024/10.21105.jose.00024.pdf)

**Comment by joonro** [comment]
@csev, the typo (??) in the citation is indeed fixed. Thank you for pointing this out.

Regarding your point (2), I created the documentation for Org-Coursepack as a mini-course using Org-Coursepack. The link to the course materials (https://joonro.github.io/Org-Coursepack/) is on the `Usage` section of the `README` on the repo. In addition, the compiled lecture notes are in the [Lectures directory](https://github.com/joonro/Org-Coursepack/tree/master/Courses/Org-Coursepack/2018%20Fall/Lectures). I can add links to these in the paper so they are easier to find.

In terms of (3), I have used this to create content for two courses, Marketing Research and Marketing Analytics. These two courses share a significant amount of materials, so I use and mix the modules to meet the need for each course. If these are what you are looking for, I would be happy to provide parts of them (e.g., a couple of lectures) as examples, as some course materials (e.g., exam questions) are private.

I hope I understood your questions correctly, if not, please let me know so I can provide you with further information or materials.

**Comment by csev** [comment]
@joonro - Thanks for the updates.   I just want to go from the paper to some sample course materials with the fewest possible clicks.  And while the Org-Coursepack documentation *technically* is a course - a link to a real course would be more satisfying.  I think the best solution would be to add another section to https://github.com/joonro/Org-Coursepack README.md titled "Courses that Use This" (or something similar) and have the links there.   You could put one or two links in the paper as well - but to me the most important thing is in the README.

**Comment by joonro** [comment]
@csev Understood! Thank you very much for your input - I agree I think an actual course content would be ideal here. I will let you know once I add this.

**Comment by joonro** [comment]
Dear @csev,

Thank you again for the constructive suggestion. Per your request, I have updated the repo with two example courses: `Introduction to Regression Analysis with Excel` and `Introduction to Regression Analysis with Python.` These example courses, which are based on actual business courses that I taught in recent years, highlight the how the Org-Coursepack can help instructors reduce redundancy and increase efficiency by utilizing modularity in creating course materials.

We believe these example courses are ideal to showcase the Org-Coursepack, since they share a large portion of course materials (both courses involve teaching fundamental statistical concepts, such as hypothesis testing and regression) but also includes some course-specific materials (one course uses Excel and the other uses Python as computational tools for analyses). Users can easily see how to mix and match course content using the Org-Coursepack from these two example courses,.

Please note that we added links to these example courses in [README](https://github.com/joonro/Org-Coursepack) as you instructed.

Thank you very much for your input. Please feel free to let us know should you have any questions or requests.

**Comment by joonro** [comment]
Dear @csev,

It has been a while since I pushed the updates following your request. I was wondering if you need anything else? Please let me know - thank you so much!

**Comment by labarba** [comment]
@whedon assign @pschloss as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @pschloss

**Comment by labarba** [comment]
@joonro We re looking for a second reviewer. Stay tuned!

**Comment by joonro** [comment]
@labarba Thank you very much! Looking forward to working with reviewers to improve the paper.

**Comment by labarba** [comment]
@gregcaporaso : Might you consider volunteering to review this submission for JOSE?

**Comment by gregcaporaso** [comment]
I'd be happy to, apologies for the delayed response.

**Comment by labarba** [comment]
@whedon add @gregcaporaso as reviewer

**Comment by whedon** [comment]
OK, @gregcaporaso is now a reviewer

**Comment by labarba** [comment]
@whedo start review

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/34. Feel free to close this issue now!
