### ISSUE TITLE
[PRE REVIEW]: treesiftr: An R package and server for viewing phylogenetic trees and data

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#28]
**Submitting author:** @wrightaprilm (<a href="http://orcid.org/0000-0003-4692-3225">April Wright</a>)
**Repository:** <a href="https://github.com/wrightaprilm/treesiftr" target ="_blank">https://github.com/wrightaprilm/treesiftr</a>
**Version:** v1.0.0
**Editor:** @juanklopper
**Reviewers:** @ethanwhite, @rachelss

**Author instructions**

Thanks for submitting your paper to JOSE @wrightaprilm. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@wrightaprilm if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00028/jose.00028/10.21105.jose.00028.pdf)

**Comment by labarba** [comment]
👋  @wrightaprilm — Thank you for your submission to JOSE. I see that you describe this as an R package for visualizing phylogenetic trees, and that the package has been used in support of workshops and a university course. 

As described, however, this submission appears to be unsuitable for publication on its own. I point you to the JOSE [Author Guidelines](http://jose.theoj.org/about#author_guidelines), which explains the type of submissions we consider. 

> JOSE accepts two types of submissions: (1) computational learning modules, created as open educational resources (OER), and (2) open-source software, created as educational technology or infrastructure.

In the first type, what would fit is a written-out tutorial, or a learning module used within the graduate course you mention in the paper, which uses this package such that the interactive computational parts are essential to complete the learning objectives.

Note that the guidelines also say:

> Computational learning modules should be complete and immediately usable for self-learning or adoption by other instructors.

In the second type (software submissions), the JOSE scope covers educational technology or infrastructure software (e.g., auto graders, course-management solutions, etc.).

We have seen in the first few submissions some software that's meant to be used in the classroom, to support specific teaching contexts. We (the editors) have been discussing how to adapt to this demand, and are still working this out. But one thing we quickly agreed on is that this type of software can only be useful to other instructors (or self-learners) if it contains fully worked-out examples as part of the documentation.

Furthermore, the expectations for the JOSE paper are greater than shown in your submission. Note that a required section is the _Statement of Need_:

> A key component of the JOSE paper is a statement by the authors, explaining the contribution made by the submitted artifacts to computationally enabled teaching and learning, and describing how they might be used by others.

Further below, it says:

> The goal is that someone reading the JOSE paper has enough information to decide if they'd be interested in adoping the learnig module or software. Readers will want to know how the content/software has been used, and how they would adopt it. They may also want to be persuaded that the authors have put careful work on creating the material, and have experience teaching with it.

Please let me know what you want to do with the submission, given this feedback. For now, it's not ready to go into review.

**Comment by labarba** [comment]
I'm sorry I missed that issue conversation. 

It looks like @moorepants was pointing you to make a submission that combines the software with the accompanying learning materials, together, as a learning module.

It's possible I'm missing something. I'm not an R person and I can't view the files directly on the repo, so I don't know if you have written-out learning materials there. If you do, perhaps the README and the paper need to explain how a reader would approach this. 

Are you submitting learning materials, in addition to the package? If yes, how would I inspect the material?

**Comment by moorepants** [comment]
@labarba, @wrightaprilm submitted https://github.com/openjournals/jose/issues/20 for a pre-inquiry and I took it upon myself to respond.

I reviewed that inquiry and saw an educational software package, worksheets, and slides that looked like a reasonably complete set of teaching materials. Furthermore, the content was written as plain text sources. I told her it looked valid to submit based on these things. Her preliminary question was wrt to the fact that the submission was a mixture of both types of submissions we accept. I suggested submitting it as an educational software package and to treat the learning module materials as supplementary materials.

@wrightaprilm I apologize for leading you astray. I wrongly assumed that software packages designed to facilitate teaching and learning were valid. It seems that only things that are considered infrastructure are allowed. Maybe there are some things that can be added or improved to meet the submission criteria.

**Comment by labarba** [comment]
> I wrongly assumed that software packages designed to facilitate teaching and learning were valid. It seems that only things that are considered infrastructure are allowed. Maybe there are some things that can be added or improved to meet the submission criteria.

Please see above, where I stated: "We (the editors) have been discussing how to adapt to this demand, and are still working this out."

We are not ruling out these types of submissions. We were just a bit blindsided by them, as they weren't included originally. 

In any case, full worked-out examples (a.k.a. tutorial) is essential.

I am not able to see slides or tutorial material on this submission. Perhaps we need breadcrumbs in the README. Also, the paper needs work, as I explained.

**Comment by labarba** [comment]
@wrightaprilm — Are you able to export your worksheets to a portable format, viewable on the repo? (like markdown). I don't have RStudio, so am not able to see this material. Also, the material is not described in the paper so I didn't get that it existed.

**Comment by labarba** [comment]
To clarify, the submission of _the worksheets_, together with the software, may be eligible under the "learning module" category.

**Comment by wrightaprilm** [comment]
Thinking about viewing worked examples without RStudio: I made a [website](https://wrightaprilm.github.io/treesiftr/index.html) for the software + exercises, which renders both exercises under the "Articles" tab. There's an [instructor's guide](https://wrightaprilm.github.io/treesiftr/articles/00-Instuctor-Guide.html), with the output that students will see via the RStudio interface, as well as screenshots of the GUI exercise answers.

In re: the Paper. I was looking at the paper on my local machine, and I couldn't see the problem. Then I looked at the repository and realized the text had gotten lost in the rollback of a prior commit. Sorry about that. The text is [here](https://github.com/wrightaprilm/treesiftr/blob/master/paper.md). I'm not sure how changes come through the journal interface. 

Supplemental slides - I saved these to [HTML](https://github.com/wrightaprilm/treesiftr/blob/master/inst/slides/TreeThinking.Rmd.html) and [PDF](https://github.com/wrightaprilm/treesiftr/blob/master/inst/slides/TreeThinking.pdf). I have to think a little more about how best to serve these outside of the RStudio application -  the PDFs look fine (though figure citations aren't appearing right), but the HTML slides look a little odd. I'm certainly willing to look more into this, if you think the module is OK to go out for review. 

I'm just coming off maternity leave, and a bit slow on the uptake, so I need this next bit to summarize and keep me on track:

- [x] Slides viewable via Git repository.
- [x] Instructor's guide with worked examples that does not require RStudio to view.
- [x] Paper text actually present in paper (sorry about this again).

**Comment by whedon** [comment]
OK, the editor is @juanklopper

**Comment by labarba** [comment]
:wave @juanklopper — I've assigned this submission to you as handling editor. Since this will be your first editing assignment, let me know if you need to bounce ideas about selecting reviewers. Check out the [Editor's Guide](https://github.com/labarba/jose/blob/master/EditorsGuide.md) I put together: it describes the editor workflow, including needed `@whedon` commands.

@wrightaprilm — My apologies for the delay in handling this submission! The beginning of semester hit me like a hurricane.

**Comment by wrightaprilm** [comment]
@labarba  I'm in grant writing jail, and hadn't noticed the passage of time. Thanks for your help handling this!

Let me know what you need from me and when you need it. I'm happy to provide some suggested reviewers who are working at the intersection of evolution and education.

**Comment by juanklopper** [comment]
@wrightaprilm I was originally assigned as editor for your submission.  Unfortunately, it has taken me this long to be in a position to assist you in taking this proposal forward.  Thanks to our editor-in-chief (EiC), @labarba for helping out.  Not to mention @moorepants .  Thanks everyone.

I note that you are in grant writing jail!  It is a special place isn't it!? :-)  I wish you all the luck.

Now that I have had some time to look at your work, I have some suggestions and questions.  Let's start with the latter.  Your last post above mentioned that you wanted to suggest a couple of reviewers.  Have you progressed with this?

@labarba has intimated to the fact that we are still negotiating the perils of inclusion criteria for the journal, and quite rightly so.  At this time, though, I want to support your submission.  Creating learning resources that others can use is something that is close to my heart.  I want to suggest that you have a look at one of the papers in our journal:  Pynamical: Model and visualize discrete nonlinear dynamical systems, chaos, and fractals.  It is available [here](https://github.com/gboeing/pynamical) .  Much like your project, it is a novel software package (in python), combined with a well developed resource infrastructure that makes it ideal for someone else to pick up and use as an educational resource.

To this end, I love the website that you added and can only suggest that you expand on it a little bit.  The same goes for the great Shiny app.  From viewing your work submitted for this proposal, I sense that your are an expert in your field.  Something, I suppose, not all of your colleagues are.  I would really recommend then that you expand on both the website and Shiny app.  Just to make it a _pick-up-and-use_ for the _less fortunate_.

I also want to suggest a quick rewrite of you actual paper.  I come from a world where we have very structured papers.  As our EiC once mentioned, the papers for JOSE are just the entry-portal to your work (for our readers).  I wouldn't mind, though, if you would consider the following structure for the rewrite:

**Summary**

A summary of the R package (one paragraph).

A summary of the R Shiny app (one paragraph).

A summary of the accompanying resources detailing the use (how to) of the package / app / accompanying resources (one paragraph).

Introduction summary on phylogenetics (one to two paragraphs).

**Statement of need**

Explain the need for this R package / Shiny app / accompanying educational resources within the context of its use (one paragraph).

Explain a use-case of the software / learning resources with inclusion of screenshots.

Let me know what you think.  And now, I'll go read up on the phylogenetics of trees, because you made me interested in it.

**Comment by wrightaprilm** [comment]
Hi Juan-

Happy to do a restructure; I'll probably get to it Friday afternoon. I send off one of two grants Friday morning, which means I get to do something fun:)

I'm happy to suggest reviewers. I have two other primarily undergraduate institution faculty in mind (one an R expert, one not) - I'll send along names and emails when I commit the restructure.

**Comment by wrightaprilm** [comment]
Alright, I committed changes to the paper that are more in line with what you've suggested. Let me know what you think.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00028/jose.00028/10.21105.jose.00028.pdf)

**Comment by juanklopper** [comment]
@wrightaprilm I have read your rewrite.  Thanks a lot.  Just to keep you informed, we have now moved on with the process and have approached some potential reviewers (I do note that you might have some suggestions and we'll keep this in mind).  Hopefully, we can update you shortly.

**Comment by wrightaprilm** [comment]
I'd like to suggest [Cathy Newman](https://www.catherinenewman.org/contact), who is another primarily undergrad institution faculty member serving similar educational audiences. [Rowan Lockwood](https://www.wm.edu/as/geology/people/faculty/lockwood_r.php) is another one who would be good.

**Comment by juanklopper** [comment]
@wrightaprilm we have our first reviewer to look at your submission.  Please hang in there until we hear back from our other requests (we will keep your suggestion in mind).

**Comment by juanklopper** [comment]
@whedon assign @ethanwhite as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @ethanwhite

**Comment by juanklopper** [comment]
@ethanwhite great to have you review this submission!  Thanks.

**Comment by labarba** [comment]
@whedon add @rachelss as reviewer

**Comment by whedon** [comment]
OK, @rachelss is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/35. Feel free to close this issue now!
