### ISSUE TITLE
[REVIEW]: ThermoState: A State manager for Thermodynamics Courses

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#33]
**Submitting author:** @bryanwweber (<a href="http://orcid.org/0000-0003-0815-9270">Bryan W. Weber</a>)
**Repository:** <a href="https://github.com/bryanwweber/thermostate" target ="_blank">https://github.com/bryanwweber/thermostate</a>
**Version:** v0.4.1
**Editor:** @kyleniemeyer
**Reviewer:** @william-pfalzgraff, @scls19fr
**Archive:** <a href="https://doi.org/10.5281/zenodo.1469771" target="_blank">10.5281/zenodo.1469771</a>

## Status

[![status](http://jose.theoj.org/papers/86ddd94292d33a3261a8f1f137a8f9f2/status.svg)](http://jose.theoj.org/papers/86ddd94292d33a3261a8f1f137a8f9f2)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/86ddd94292d33a3261a8f1f137a8f9f2"><img src="http://jose.theoj.org/papers/86ddd94292d33a3261a8f1f137a8f9f2/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/86ddd94292d33a3261a8f1f137a8f9f2/status.svg)](http://jose.theoj.org/papers/86ddd94292d33a3261a8f1f137a8f9f2)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bryanwweber/thermostate" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@william-pfalzgraff & @scls19fr, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @kyleniemeyer know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bryanwweber/thermostate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.1)?
- [x] **Authorship:** Has the submitting author (@bryanwweber) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bryanwweber/thermostate">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.4.1)?
- [x] **Authorship:** Has the submitting author (@bryanwweber) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @william-pfalzgraff, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00033/jose.00033/10.21105.jose.00033.pdf)

**Comment by kyleniemeyer** [comment]
👋 @bryanwweber @william-pfalzgraff @scls19fr the review will take place in this issue. Please note the two reviewer checklists above, and you can leave additional review comments here.

You can also leave specific fixes/suggestions/issues as issues in the repo of the submission, just make sure to either mention *this* issue in those or vice versa so we can see the connection.

**Comment by bryanwweber** [comment]
Hi @william-pfalzgraff @scls19fr Thank you for agreeing to review this! In looking at the review issue here, I realized there are no installation instructions in the docs... The easiest way is to install with conda or pip, either of which should work. I think you have to use Python 3.5 or 3.6 because CoolProp is only available for those versions; with pip it has to be 3.5, with conda, you can use my CoolProp package for 3.6 with the following command (that should automatically install CoolProp):

```conda install -c bryanwweber thermostate```

You also need a channel that has pint if you're using conda; I'd recommend `conda-forge`. Please let me know if you need help installing so you can check the functionality of the software, and I'll certainly update the docs as part of this review.

Also to be fixed during this review: bryanwweber/thermostate#10 bryanwweber/thermostate#11 bryanwweber/thermostate#12

**Comment by scls19fr** [comment]
Hi @bryanwweber ,

Thanks for noticing the lack of install instructions.
Fixing doc could also be a nice improvement that you can probably also achieve.

This project relies on previous work about Python for scientists (Python for Scientific Computing, Python for Scientists and Engineers...) . Maybe you could also cite Matplotlib and Numpy at the very least.
Citing Pint may be more complicated for now according https://github.com/hgrecco/pint/issues/717 but citing it like you did is probably not an issue.
Some of your examples (in the `docs` folder are using IPython) maybe you can also cite it.
You can probably fix all that before going beyond.

About "Statement of need", my feeling is quite mixed, I noticed that CoolProp have a "State" API also, so I wonder why such a package is not include directly into CoolProp?
But maybe this kind of question is out of the scope of this review.
Anyway giving an usage example with non SI units with both libraries could give readers an interest in using Thermostate instead of using directly Coolprop.

Best regards

**Comment by william-pfalzgraff** [comment]
Hi @bryanwweber, thanks for the install instructions.  Having detailed install instructions directly int he readme for thermostate would be very helpful.

Do I understand correctly that pip can _only_ be used if I am using python 3.5, and not python 3.6?  [Link to issue](https://github.com/bryanwweber/thermostate/issues/13).

**Comment by bryanwweber** [comment]
@william-pfalzgraff I think the way to say it is, if you're using pip to install, you *must* be using Python 3.5 because CoolProp is only available for Python 3.5 from PyPI. If you're using conda, you can use either Python 3.5 or 3.6. Python 3.7 is supported by ThermoState (because ThermoState itself is pure-Python), but binary installers for CoolProp are not yet available for Python 3.7; you can of course build CoolProp yourself and then separately install ThermoState if you wish.

@scls19fr You said
> You can probably fix all that before going beyond.

Do you want me to fix these citations in the paper before continuing with the review? I think your comment about the statement of need is quite relevant, and I will respond a bit later 😄

**Comment by kyleniemeyer** [comment]
@scls19fr From my perspective, @bryanwweber can work on the issues you have raised while you work through the remaining review items, and then we can return to the paper itself once he revises it. This is meant to be an iterative continuous process.

**Comment by scls19fr** [comment]
Thanks @bryanwweber for this very clear explanation!
LGTM when https://github.com/bryanwweber/thermostate/pull/15/ will be merged

**Comment by william-pfalzgraff** [comment]
One other minor comment/question from me and then likewise LGTM when  bryanwweber/thermostate#15 is merged.  

My comment/question is about community guidelines.  Does posting the project to Github constitute "Clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support" in the sense that third parties could do all of these things through Github?  Or is more required, e.g. a statement in the README?  @kyleniemeyer, do you have any thoughts?

If there is not already such a statement, it would be nice to add something to the README about how best to contact the author, how to report bugs, that pull requests are welcomed (if they are) etc.  

Otherwise, looks good!

**Comment by bryanwweber** [comment]
@william-pfalzgraff There are 2 files that cover this: the [Contributing instructions](https://github.com/bryanwweber/thermostate/blob/master/CONTRIBUTING.md) and the [Contributor Covenant Code of Conduct](https://github.com/bryanwweber/thermostate/blob/master/CODE_OF_CONDUCT.md). I've added a note linking to these files into the README! Thank you! 😄 

@kyleniemeyer What should I do now? Do I make a new release of the software incorporating these suggestions?

**Comment by kyleniemeyer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00033/jose.00033/10.21105.jose.00033.pdf)

**Comment by kyleniemeyer** [comment]
@bryanwweber a few paper comments/edits:

- why is "manager" lowercase in the paper title? Although I personally prefer sentence-case, it looks like you are using title case, so shouldn't that be capitalized?
- Could you add more-complete affiliation info? (e.g., city, state, country—what you'd typically see in a paper)
- First paragraph in Statement of Need: I believe "students" needs an apostrophe
- Second paragraph in Statement of Need: "don't" -> "do not"
- Third paragraph in Statement of Need: is "utilize" really necessary there? I think "use" would work just fine.
- In the first code snippet, I'm wondering if you should include where `Q_` and `State` come from. I realize that the repo itself has more-complete use examples, but I think those in the paper would be more useful if they had those extra imports.
- For the Oliphant reference, if this is a book I believe more details are needed. If this is an electronic-only reference, then we need a DOI or URL.

Finally, this isn't so much an edit but a general question on the package: why did you choose short single-letter abbreviations for properties rather than writing out the names (e.g., `T, p` vs `temperature, pressure`)? I would think the latter would be more clear (and thus more Pythonic)... the main benefit I can see is that the variables match those when setting using attributes (e.g., `state.Tp = ...`).

**Comment by bryanwweber** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00033/jose.00033/10.21105.jose.00033.pdf)

**Comment by kyleniemeyer** [comment]
@bryanwweber LGTM! And got it, that makes sense.

OK, please archive the entire repo and provide the DOI here.

**Comment by kyleniemeyer** [comment]
@labarba This is ready for your attention now

**Comment by bryanwweber** [comment]
@kyleniemeyer The doi is 10.5281/zenodo.1469771 :tada:

**Comment by kyleniemeyer** [comment]
@bryanwweber thanks—I forgot to ping @labarba first (sorry!), so if she has any additional changes you may need to do that again. Stay tuned!

**Comment by labarba** [comment]
@bryanwweber The paper has you as the sole author, but the Zenodo archive does not match that. It could be that Zenodo grabbed authors automatically from GitHub commits, and you need to manually edit the entry.

**Comment by bryanwweber** [comment]
Thanks @labarba! I changed the Zenodo entry so I'm the sole author there too. Any other places you can see to improve this submission?

**Comment by labarba** [comment]
It looks like a great piece of software for teaching thermo and I can't wait to share it with my colleagues!

**Comment by labarba** [comment]
@whedon set 10.5281/zenodo.1469771  as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.1469771" target="_blank">10.5281/zenodo.1469771</a> is the archive.

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/1

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/1, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00033/status.svg)](https://doi.org/10.21105/jose.00033)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00033">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00033/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00033/status.svg
   :target: https://doi.org/10.21105/jose.00033
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00033/status.svg)](https://doi.org/10.21105/jose.00033)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future.
- Making a small donation to support our running costs here: https://www.flipcause.com/secure/cause_pdetails/Mjk3ODA=

**Comment by labarba** [comment]
This paper is now published in JOSE !!!

@william-pfalzgraff, @scls19fr — Thank you for your review and being a part in this adventure in new publishing!

**Comment by bryanwweber** [comment]
@labarba @kyleniemeyer @william-pfalzgraff @scls19fr Thank you for your help and work getting this paper published!

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
