### ISSUE TITLE
[PRE REVIEW]: StateMint: A Set of Tools for Determining Symbolic Dynamic System Models Using Linear Graph Methods

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#38]
**Submitting author:** @CameronDevine (<a href="http://orcid.org/0000-0002-6579-111X">Cameron Devine</a>)
**Repository:** <a href="https://github.com/CameronDevine/StateMint" target ="_blank">https://github.com/CameronDevine/StateMint</a>
**Version:** 2.0.0
**Editor:** @moorepants
**Reviewers:** @chrisdembia, @gboeing

**Author instructions**

Thanks for submitting your paper to JOSE @CameronDevine. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@CameronDevine if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #38 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/38 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:47:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-50d5912cf72a/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00038/jose.00038/10.21105.jose.00038.pdf)

**Comment by CameronDevine** [comment]
Looking over the reviewer lists I have identified the following as good candidates.

From the JOSE list:
- @moorepants

From the JOSS list:
- @acolum
- @vsoch

**Comment by acolum** [comment]
@CameronDevine  Thank you for tagging me, but unfortunately, I'm not able to review at this time.

**Comment by labarba** [comment]
@whedon set @moorepants as editor

**Comment by labarba** [comment]
:wave @moorepants — I assigned you your first paper to handle as JOSE editor! This is one is a good fit for you.

**Comment by labarba** [comment]
@whedon assign @moorepats as editor

**Comment by whedon** [comment]
OK, the editor is @moorepats

**Comment by labarba** [comment]
@whedon assign @moorepants as editor

**Comment by whedon** [comment]
OK, the editor is @moorepants

**Comment by labarba** [comment]
👋  @moorepants — After a couple of failed attempts, I've now assigned you your first JOSE paper to edit! This one is a good fit for you. Godspeed!

**Comment by moorepants** [comment]
I have the first reviewer. Chris Dembia is a PhD candidate at Stanford in the Neuromuscular Biomechanics Lab and a core developer on the Simbody and Opensim projects. He has also worked with Python and SymPy.

@whedon add @chrisdembia as reviewer

**Comment by moorepants** [comment]
@vsoch I see that you gave a thumbs up to the last message and were mentioned above. Would you like to be a reviewer of this article?

**Comment by moorepants** [comment]
@whedon assign @chrisdembia as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @chrisdembia

**Comment by chrisdembia** [comment]
Please address the following questions in the way you find most appropriate.

1. For what size problems do you expect the tools to function well? It might be good to document the problem size you expect. For example, it seems that the web interface might not properly display results for problems with hundreds of equations and variables.

2. What are some concrete intended use case? Will the software be used in a class at your university?

3. Are there other similar tools out there?

4. It seems your submission is missing some items listed in the [Reviewer Guidelines](http://jose.theoj.org/about#reviewer_guidelines):

a. "The online repository of the software or learning module needs to contain guidelines for potential contributors who may want to: submit changes, make improvements or report issues."
b. "Pedagogical soundness...The authors should briefly explain their design in the JOSE paper."
c. There should be clear guidelines for third-parties wishing to: Contribute to the software/module, Report issues or problems with the software/module, Seek support.

I have submitted a PR to your StateMint with additional comments and suggested changes.


Web interface
=============

The web interface has a beautiful design, and is, overall, easy to follow.

1. What does the SAVE button do? I entered a name but it wasn't obvious what happened after that. I eventually discovered that the "OPEN EXISTING" button showed the systems I had saved, but this was not obvious and I am still confused about where these files actually reside. What happens if I close the browser window? Do these saved files disappear?
2. The DOWNLOAD button provides an RND file. What is this file format? I haven't heard of it before and I didn't find any description of it.
3. If I enter incorrect input and hit "= CALCULATE", I get the flashing hexagons forever. If I scroll down, I see "We're sorry. The function has encountered an error". Ideally, this message would be shown immediately so that the user does not keep waiting unnecessarily.
4. It's unclear if the formatting of the "Results" pane will scale well to many equations.
5. Where do you document the "Upload a photo" functionality of the web interface? It's unclear what this does or what the photo should be.
6. For each example, consider a brief description of what system is being modeled.

WEB interface tutorial
The figures in the tutorial are well-designed. The choice of example is good. However, the second half of the tutorial is confusing and is not sufficiently clear for someone with a traditional system dynamics background and is not familiar with linear graph theory.
1. The tutorial would benefit from making clear which parts of the tutorial describe what a user must do to prepare input versus describing what the StateMint software does. It seems that the user must manually derive elemental, continuity, and compatibility equations, and the software uses these equations to provide state and output equations. This could be made clearer.
2. There are numbers on the figures in the Normal Tree section (e.g., 1, 2, 3, 4), but you do not describe the meaning of these numbers.
3. The writing would benefit from the use of the active voice instead of the passive voice.


Python
======
It's atypical to put all the code in __init__.py. Please create more descriptive Python files.

Example.ipynb
1. The first paragraph seems incorrect (there are 3 methods for using StateMint, not only 2).
2. Out[5] shows $(t)$ on its own. Placing $t$ in parentheses like this seems odd; is there an error?


Mathematica
===========
I installed a trial of Mathematica and ran the example without errors.

Please state the version of Mathematica with which you tested StateMint.

**Comment by labarba** [comment]
👋  @moorepants — Did you plan to have a second reviewer for this submission?

@chrisdembia — Thanks for providing these comments to the author… they can start working on revisions already, but with respect to the JOSE process, we're still in the PRE-REVIEW issue. When the editor has finished assigning the reviewer(s) they recruit for a submission, they start the review with a command here (`@whedon start review`), which opens a _new_ issue where the review is handled. That new issue will have a review checklist at the top. See examples by following the link to a past review from one of our published papers: http://jose.theoj.org

**Comment by moorepants** [comment]
Yes, I'm trying to get a second reviewer. It isn't clear to me if we can go to the actual review issue without that person yet. Should we?

**Comment by labarba** [comment]
Well ... if you start the review now, then adding a second reviewer on the review issue will be a manual process (edit the first post to copy and paste the checklist, manually add user to team). 

You need to add the reviewer here, _then_ start the review to automatically get both the checklist for both reviewers and their permissions to edit.

**Comment by moorepants** [comment]
Ok, I'm still working on the second reviewer. We will wait till I get it. In the mean time, @CameronDevine can informally work on @chrisdembia's suggestions.

**Comment by labarba** [comment]
JOSE published the [Pynamical](http://jose.theoj.org/papers/8e0d222df1d4e63dcf61bebcb643714a) package as one of its first papers. Maybe its author, @gboeing could be interested in contributing a review of the current submission?

**Comment by gboeing** [comment]
@labarba @moorepants sure, I could review this.

**Comment by labarba** [comment]
@whedon add @gboeing as reviewer

**Comment by whedon** [comment]
OK, @gboeing is now a reviewer

**Comment by labarba** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/44. Feel free to close this issue now!

**Comment by moorepants** [comment]
Great, thanks!
