### ISSUE TITLE
[REVIEW]: StateMint: A Set of Tools for Determining Symbolic Dynamic System Models Using Linear Graph Methods

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#44]
**Submitting author:** @CameronDevine (<a href="http://orcid.org/0000-0002-6579-111X">Cameron Devine</a>)
**Repository:** <a href="https://github.com/CameronDevine/StateMint" target ="_blank">https://github.com/CameronDevine/StateMint</a>
**Version:** 2.1.0
**Editor:** @moorepants
**Reviewer:** @chrisdembia, @gboeing
**Archive:** <a href="https://doi.org/10.5281/zenodo.2633330" target="_blank">10.5281/zenodo.2633330</a>

## Status

[![status](http://jose.theoj.org/papers/7caec95b5db5c18d8a14cbc42fef7bb7/status.svg)](http://jose.theoj.org/papers/7caec95b5db5c18d8a14cbc42fef7bb7)

Status badge code:

```
HTML: <a href="http://jose.theoj.org/papers/7caec95b5db5c18d8a14cbc42fef7bb7"><img src="http://jose.theoj.org/papers/7caec95b5db5c18d8a14cbc42fef7bb7/status.svg"></a>
Markdown: [![status](http://jose.theoj.org/papers/7caec95b5db5c18d8a14cbc42fef7bb7/status.svg)](http://jose.theoj.org/papers/7caec95b5db5c18d8a14cbc42fef7bb7)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/CameronDevine/StateMint" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@chrisdembia & @gboeing, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/jose-reviews/invitations

The reviewer guidelines are available here: https://jose.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @moorepants know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CameronDevine/StateMint">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 2.1.0
- [x] **Authorship:** Has the submitting author (@CameronDevine) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSE conflict of interest policy](https://github.com/openjournals/jose/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSE code of conduct](https://jose.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/CameronDevine/StateMint">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 2.1.0
- [x] **Authorship:** Has the submitting author (@CameronDevine) made substantial contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation? (and documentation is sufficient?)
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **Installation instructions:** Is there a clearly stated list of dependencies? (Ideally these should be handled with an automated package management solution.)
- [x] **Example usage:** Do the authors include examples of how to use the software?
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state the need for this software and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @chrisdembia, it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/jose-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/jose-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00044/jose.00044/10.21105.jose.00044.pdf)

**Comment by labarba** [comment]
👋  @chrisdembia, @gboeing — Thank you for agreeing to review for JOSE! This is where the action happens: work your way through the review checklist, feel free to ask questions or post comments here, and also open issues in the submission repository as needed. Godspeed!

**Comment by labarba** [comment]
@CameronDevine — please bear in mind the comments that @chrisdembia posted on the Pre-Review issue: https://github.com/openjournals/jose-reviews/issues/38#issuecomment-457782845

@chrisdembia — feel free to re-post those comments here, if you wish.

**Comment by moorepants** [comment]
Yes, @chrisdembia please repost those comments here, so we keep things in one place.

**Comment by chrisdembia** [comment]
Please address the following questions in the way you find most appropriate.

1. For what size problems do you expect the tools to function well? It might be good to document the problem size you expect. For example, it seems that the web interface might not properly display results for problems with hundreds of equations and variables.

2. What are some concrete intended use case? Will the software be used in a class at your university?

3. Are there other similar tools out there?

4. It seems your submission is missing some items listed in the [Reviewer Guidelines](http://jose.theoj.org/about#reviewer_guidelines):

a. "The online repository of the software or learning module needs to contain guidelines for potential contributors who may want to: submit changes, make improvements or report issues."
b. "Pedagogical soundness...The authors should briefly explain their design in the JOSE paper."
c. There should be clear guidelines for third-parties wishing to: Contribute to the software/module, Report issues or problems with the software/module, Seek support.

I have submitted a PR to your StateMint with additional comments and suggested changes.


Web interface
=============

The web interface has a beautiful design, and is, overall, easy to follow.

1. What does the SAVE button do? I entered a name but it wasn't obvious what happened after that. I eventually discovered that the "OPEN EXISTING" button showed the systems I had saved, but this was not obvious and I am still confused about where these files actually reside. What happens if I close the browser window? Do these saved files disappear?
2. The DOWNLOAD button provides an RND file. What is this file format? I haven't heard of it before and I didn't find any description of it.
3. If I enter incorrect input and hit "= CALCULATE", I get the flashing hexagons forever. If I scroll down, I see "We're sorry. The function has encountered an error". Ideally, this message would be shown immediately so that the user does not keep waiting unnecessarily.
4. It's unclear if the formatting of the "Results" pane will scale well to many equations.
5. Where do you document the "Upload a photo" functionality of the web interface? It's unclear what this does or what the photo should be.
6. For each example, consider a brief description of what system is being modeled.

WEB interface tutorial
The figures in the tutorial are well-designed. The choice of example is good. However, the second half of the tutorial is confusing and is not sufficiently clear for someone with a traditional system dynamics background and is not familiar with linear graph theory.
1. The tutorial would benefit from making clear which parts of the tutorial describe what a user must do to prepare input versus describing what the StateMint software does. It seems that the user must manually derive elemental, continuity, and compatibility equations, and the software uses these equations to provide state and output equations. This could be made clearer.
2. There are numbers on the figures in the Normal Tree section (e.g., 1, 2, 3, 4), but you do not describe the meaning of these numbers.
3. The writing would benefit from the use of the active voice instead of the passive voice.


Python
======
It's atypical to put all the code in __init__.py. Please create more descriptive Python files.

Example.ipynb
1. The first paragraph seems incorrect (there are 3 methods for using StateMint, not only 2).
2. Out[5] shows $(t)$ on its own. Placing $t$ in parentheses like this seems odd; is there an error?


Mathematica
===========
I installed a trial of Mathematica and ran the example without errors.

Please state the version of Mathematica with which you tested StateMint.

**Comment by moorepants** [comment]
@CameronDevine, you are welcome to start work on addressing @chrisdembia's review if you have not yet started.

@gboeing, we have not heard from you in over a week. Can you update us on the status of your review?

**Comment by gboeing** [comment]
@moorepants I'll be able to complete this by early next week.

**Comment by moorepants** [comment]
Sounds great!

**Comment by moorepants** [comment]
@gboeing Can you give us a status update?

**Comment by gboeing** [comment]
Overall, the software looks useful and the web interface is very attractively designed. The paper is pretty clear and well-written. Regarding revisions/issues: rather than duplicating them all here, I'll start by saying that @chrisdembia's review covered most of the points I wanted to make. In addition, I have opened two issues in the software's repo https://github.com/CameronDevine/StateMint/issues/9 and https://github.com/CameronDevine/StateMint/issues/10.

**Comment by moorepants** [comment]
Fantastic! @chrisdembia and @gboeing, thank you both for you careful and thoughtful reviews.

@CameronDevine The reviewers' comments and requests seem appropriate. The ball is now in your court to address the reviews. Please do so and keep us up-to-date here on your progress or with any questions/comments you have.

**Comment by CameronDevine** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00044/jose.00044/10.21105.jose.00044.pdf)

**Comment by CameronDevine** [comment]
I have addressed the issues in @chrisdembia's pull request, but am waiting to close it until I get confirmation I have sufficiently answered his questions. I have a few more items to address in @chrisdembia's comment on this issue. After that I will work on @gboeing's issues.

**Comment by CameronDevine** [comment]
@chrisdembia Below are my responses to your comments.

> 1. For what size problems do you expect the tools to function well? It might be good to document the problem size you expect. For example, it seems that the web interface might not properly display results for problems with hundreds of equations and variables.

The question about the web interface is addressed below. Doing a couple tests I found that solving for the state equation of N independent RC filters is O(N). However, solving N cascaded RC filters was O(e^N^2). So far I have not encountered a problem that was not able to be solved in a reasonable amount of time, except those which I fabricated to test the performance.

> 2. What are some concrete intended use case? Will the software be used in a class at your university?

Prof. Rico Picone at St. Martin's University and Prof. Joseph Garbini at The University of Washington are both planning to use this tool in their system dynamics and control systems classes. This tool will allow students to more easily complete homework problems because they will not have to perform as much algebra.

> 3. Are there other similar tools out there?

I believe there are similar tools available for use with Bond Graphs, but I do not know of any for use with Linear Graphs.

> 4. It seems your submission is missing some items listed in the [Reviewer Guidelines](http://jose.theoj.org/about#reviewer_guidelines):
>
> a. "The online repository of the software or learning module needs to contain guidelines for potential contributors who may want to: submit changes, make improvements or report issues."

This has been added.

> b. "Pedagogical soundness...The authors should briefly explain their design in the JOSE paper."

Would the addition to the paper of an explanation of the algorithm used to find the differential equations be enough to satisfy this requirement?

> c. There should be clear guidelines for third-parties wishing to: Contribute to the software/module, Report issues or problems with the software/module, Seek support.

This has been added.

# Web interface

> 1. What does the SAVE button do? I entered a name but it wasn't obvious what happened after that. I eventually discovered that the "OPEN EXISTING" button showed the systems I had saved, but this was not obvious and I am still confused about where these files actually reside. What happens if I close the browser window? Do these saved files disappear?

These files are saved in your browser as cookies. They are set to expire after 10 years, but they may be deleted before that happens. I understand how this could be confusing so I added a note about this in the save dialog.

> 2. The DOWNLOAD button provides an RND file. What is this file format? I haven't heard of it before and I didn't find any description of it.

This file is actually a JPEG image with the system data added as metadata. The RND name was created back when we were calling this tool by its initial name, State Model RnD. I would welcome any suggestions on what file extension to use, and where to document this.

> 3. If I enter incorrect input and hit "= CALCULATE", I get the flashing hexagons forever. If I scroll down, I see "We're sorry. The function has encountered an error". Ideally, this message would be shown immediately so that the user does not keep waiting unnecessarily.

This has been fixed.

> 4. It's unclear if the formatting of the "Results" pane will scale well to many equations.

A system of 15 independent RC filters can be solved using this [link](https://statemint.stmartin.edu/?%7B%22InVars%22%3A%20%22Vs1%2C%20Vs2%2C%20Vs3%2C%20Vs4%2C%20Vs5%2C%20Vs6%2C%20Vs7%2C%20Vs8%2C%20Vs9%2C%20Vs10%2C%20Vs11%2C%20Vs12%2C%20Vs13%2C%20Vs14%2C%20Vs15%22%2C%20%22StVarElEqns%22%3A%20%22Vc1%27%3DIc1/C1%2C%5CnVc2%27%3DIc2/C2%2C%5CnVc3%27%3DIc3/C3%2C%5CnVc4%27%3DIc4/C4%2C%5CnVc5%27%3DIc5/C5%2C%5CnVc6%27%3DIc6/C6%2C%5CnVc7%27%3DIc7/C7%2C%5CnVc8%27%3DIc8/C8%2C%5CnVc9%27%3DIc9/C9%2C%5CnVc10%27%3DIc10/C10%2C%5CnVc11%27%3DIc11/C11%2C%5CnVc12%27%3DIc12/C12%2C%5CnVc13%27%3DIc13/C13%2C%5CnVc14%27%3DIc14/C14%2C%5CnVc15%27%3DIc15/C15%22%2C%20%22OtherElEqns%22%3A%20%22IR1%3DVR1/R1%2C%5CnIR2%3DVR2/R2%2C%5CnIR3%3DVR3/R3%2C%5CnIR4%3DVR4/R4%2C%5CnIR5%3DVR5/R5%2C%5CnIR6%3DVR6/R6%2C%5CnIR7%3DVR7/R7%2C%5CnIR8%3DVR8/R8%2C%5CnIR9%3DVR9/R9%2C%5CnIR10%3DVR10/R10%2C%5CnIR11%3DVR11/R11%2C%5CnIR12%3DVR12/R12%2C%5CnIR13%3DVR13/R13%2C%5CnIR14%3DVR14/R14%2C%5CnIR15%3DVR15/R15%22%2C%20%22Constraints%22%3A%20%22Ic1%3DIR1%2C%5CnIc2%3DIR2%2C%5CnIc3%3DIR3%2C%5CnIc4%3DIR4%2C%5CnIc5%3DIR5%2C%5CnIc6%3DIR6%2C%5CnIc7%3DIR7%2C%5CnIc8%3DIR8%2C%5CnIc9%3DIR9%2C%5CnIc10%3DIR10%2C%5CnIc11%3DIR11%2C%5CnIc12%3DIR12%2C%5CnIc13%3DIR13%2C%5CnIc14%3DIR14%2C%5CnIc15%3DIR15%2C%5CnVR1%3DVs1-Vc1%2C%5CnVR2%3DVs2-Vc2%2C%5CnVR3%3DVs3-Vc3%2C%5CnVR4%3DVs4-Vc4%2C%5CnVR5%3DVs5-Vc5%2C%5CnVR6%3DVs6-Vc6%2C%5CnVR7%3DVs7-Vc7%2C%5CnVR8%3DVs8-Vc8%2C%5CnVR9%3DVs9-Vc9%2C%5CnVR10%3DVs10-Vc10%2C%5CnVR11%3DVs11-Vc11%2C%5CnVR12%3DVs12-Vc12%2C%5CnVR13%3DVs13-Vc13%2C%5CnVR14%3DVs14-Vc14%2C%5CnVR15%3DVs15-Vc15%22%2C%20%22OutputVars%22%3A%20%22Vc1%2C%20Vc2%2C%20Vc3%2C%20Vc4%2C%20Vc5%2C%20Vc6%2C%20Vc7%2C%20Vc8%2C%20Vc9%2C%20Vc10%2C%20Vc11%2C%20Vc12%2C%20Vc13%2C%20Vc14%2C%20Vc15%22%7D). This shows how the page can be scrolled horizontally to view the entire equation.

> 5. Where do you document the "Upload a photo" functionality of the web interface? It's unclear what this does or what the photo should be.

I noticed a bug related to this, which is now fixed. This image is displayed for reference while entering equations on the "Enter System Equations" pane.

> 6. For each example, consider a brief description of what system is being modeled.

This has been added.

## WEB interface tutorial

> 1. The tutorial would benefit from making clear which parts of the tutorial describe what a user must do to prepare input versus describing what the StateMint software does. It seems that the user must manually derive elemental, continuity, and compatibility equations, and the software uses these equations to provide state and output equations. This could be made clearer.

The tutorial has been updated.

> 2. There are numbers on the figures in the Normal Tree section (e.g., 1, 2, 3, 4), but you do not describe the meaning of these numbers.

This has been added.

> 3. The writing would benefit from the use of the active voice instead of the passive voice.

I will be working on this over the next couple of days.

# Python

> It's atypical to put all the code in \_\_init\_\_.py. Please create more descriptive Python files.

The Python library has been moved to a more descriptive filename.

## Example.ipynb

> 1. The first paragraph seems incorrect (there are 3 methods for using StateMint, not only 2).

You are correct. This has been changed.

> 2. Out[5] shows $(t)$ on its own. Placing $t$ in parentheses like this seems odd; is there an error?

That is really strange. Running the Jupyter notebook on my machine this issue is not present. I have contacted GitHub about this issue.

# Mathematica
 
> Please state the version of Mathematica with which you tested StateMint.

This has been added to the Mathematica folder readme.

**Comment by moorepants** [comment]
> Would the addition to the paper of an explanation of the algorithm used to find the differential equations be enough to satisfy this requirement?

The pedagogical soundness is asking for you to justify why your software/lesson is good for teaching and learning. Backing this with some educational research evidence is ideal.

**Comment by CameronDevine** [comment]
Thank you for the clarification @moorepants.

**Comment by CameronDevine** [comment]
@moorepants and @chrisdembia, the following statement is already included in the paper.

> Finally, the set of equations can be reduced to a system of first-order differential equations
in state and input variables and their time-derivatives, alone. It is in these last two steps,
especially the very last, that a student, manually reducing the set of equations, will often make some minor mistake. This is typically of a “book keeping” variety that, if it
teaches the student anything, it is not system dynamics. Instead, the student can be
easily discouraged and confused about where they have made their mistake. Fortunately,
the software tools presented here will automate the algebraic reduction. These will allow
students to focus on understanding the process of dynamic system modeling.

Prof. Rico Picone and Prof. Joseph Garbini both have many years of experience teaching system dynamics using linear graph methods. They both agree that this is the area where most students struggle. We could add more to the paper to explain this.

We also could distribute a survey to Prof. Rico Picone's current students, possibly including some of the questions below.

> 1. At which step in the state-space modeling algorithm do you most frequently make a mistake? [list steps of algorithm]
> 2. If there was an effective tool that automated step X [the thing StateMint does], would you find that it helps your learning process? If yes, why? If no, why not?
> 3. Consider the tool at statemint.stmartin.edu. Try an example. Do you think this is an effective tool for the automation of step X?

Which of these do you think would best show the pedagogical soundness of this tool?

**Comment by moorepants** [comment]
@chrisdembia @gboeing Can you both comment on @CameronDevine's last post? I'll defer to the reviewers on deciding how to handle the pedagogical soundness requirement. I can help provide facts and clarifications.

**Comment by gboeing** [comment]
In my opinion, a survey is not *necessary* but it would be nice. Certainly more explanation regarding your comment ("Prof. Rico Picone and Prof. Joseph Garbini both have many years of experience teaching system dynamics using linear graph methods. They both agree that this is the area where most students struggle. We could add more to the paper to explain this.") would be helpful to elucidate too.

**Comment by labarba** [comment]
Hi everybody! 
We don't require formal evaluation of the learning module, but we expect the author to describe their instructional design and the pedagogy behind it.

I see both reviewers have some items of their review lists unchecked. Are you working on addressing some of the reviewer comments, @CameronDevine?

**Comment by moorepants** [comment]
@chrisdembia @gboeing @CameronDevine Can you all please provide an update as to the status of this review?

**Comment by CameronDevine** [comment]
@moorepants I believe I have fixed all but two of the issues brought up by @chrisdembia and @gboeing.

1. I will be adding more to the statement of need in the paper later today, and I should have a new version which can be reviewed in the next couple of days.

2. camerondevine/StateMint#10 is still open, and I will use Zenodo to get a DOI number for the source code after the other changes have been approved by @chrisdembia and @gboeing.

**Comment by CameronDevine** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00044/jose.00044/10.21105.jose.00044.pdf)

**Comment by CameronDevine** [comment]
@chrisdembia and @gboeing, I believe I have addressed all of your comments. If there is anything outstanding please let me know.

**Comment by moorepants** [comment]
@chrisdembia and @gboeing Can you both reply and let me know if you feel everything has been addressed?

**Comment by gboeing** [comment]
Looks good to me.

**Comment by labarba** [comment]
Hi @gboeing — if you're ready to recommend publication, can you check off your remaining items in the checklist? Cheers!

**Comment by chrisdembia** [comment]
The checklist above contains an item " A statement of need: Do the authors clearly state the need for this software and who the target audience is?" under **Documentation**. I found a statement of need in the paper but not in the documentation. Where can I find such a statement?

**Comment by labarba** [comment]
The request for a Statement of Need refers to the JOSE paper.

**Comment by chrisdembia** [comment]
There are two requests for a statement of need: one for the paper and one for the documentation.

**Comment by moorepants** [comment]
Yes, that is the case. @labarba Can you clarify?

**Comment by labarba** [comment]
I think this could be an editing mistake on creating the checklists. What would be a reason to request this in the software documentation? I rather think it's enough to have it in the paper.

**Comment by moorepants** [comment]
Ok, thank you for the clarification.

**Comment by moorepants** [comment]
@chrisdembia Other than that it seems you have everything checked off. Are good on all non-checklist items you brought up?

**Comment by chrisdembia** [comment]
Yes. LGTM.

**Comment by moorepants** [comment]
@CameronDevine I recommend your article for publishing. Can you please mint a DOI? (https://github.com/CameronDevine/StateMint/issues/10)

**Comment by CameronDevine** [comment]
@moorepants would you mind if I rolled the version number to 2.1.0 first?

**Comment by moorepants** [comment]
Yes, you can make the version number anything you want. Please update in the paper once changed.

**Comment by labarba** [comment]
@CameronDevine : You can try running `@whedon set v2.1.0 as version` here, but I'm not sure if authors have permission to run that command.That will update the version in this issue and the paper's side bar.

**Comment by CameronDevine** [comment]
@whedon set 2.1.0 as version

**Comment by whedon** [comment]
I'm sorry @CameronDevine, I'm afraid I can't do that. That's something only editors are allowed to do.

**Comment by CameronDevine** [comment]
@moorepants can you change the version to 2.1.0? I also uplaoded the code to Zendodo, (doi: 10.5281/zenodo.2633330).

**Comment by moorepants** [comment]
@whedon set 2.1.0 as version

**Comment by whedon** [comment]
OK. 2.1.0 is the version.

**Comment by moorepants** [comment]
@whedon set 10.5281/zenodo.2633330 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.2633330" target="_blank">10.5281/zenodo.2633330</a> is the archive.

**Comment by moorepants** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00044/jose.00044/10.21105.jose.00044.pdf)

**Comment by moorepants** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by moorepants** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #44 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     49      0 --:--:-- --:--:-- --:--:--    49
pandoc: paper.md: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the Crossref XML

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by moorepants** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #44 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     43      0 --:--:-- --:--:-- --:--:--    43
sh: 0: getcwd() failed: No such file or directory
pandoc: 10.21105.jose.00044.pdf: openBinaryFile: does not exist (No such file or directory)
Looks like we failed to compile the PDF

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by moorepants** [comment]
@labarba Am I missing something here? Not quite sure why this is giving an error.

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00044/jose.00044/10.21105.jose.00044.pdf)

**Comment by labarba** [comment]
@whedon accept

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.7717/peerj-cs.103 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
Check final proof :point_right: https://github.com/openjournals/jose-papers/pull/29

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/jose-papers/pull/29, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by moorepants** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
I'm sorry @moorepants, I'm afraid I can't do that. That's something only editor-in-chiefs are allowed to do.

**Comment by labarba** [comment]
@whedon accept deposit=true

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSE!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/jose-papers/pull/30
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/jose.00044](https://doi.org/10.21105/jose.00044)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by labarba** [comment]
Congratulations, @CameronDevine, your JOSE paper is now published!

Big thanks to the editor: @moorepants, and the reviewers: @chrisdembia, @gboeing — your contribution is so important 🙏

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://jose.theoj.org/papers/10.21105/jose.00044/status.svg)](https://doi.org/10.21105/jose.00044)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jose.00044">
  <img src="https://jose.theoj.org/papers/10.21105/jose.00044/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://jose.theoj.org/papers/10.21105/jose.00044/status.svg
   :target: https://doi.org/10.21105/jose.00044
```
This is how it will look in your documentation:

[![DOI](https://jose.theoj.org/papers/10.21105/jose.00044/status.svg)](https://doi.org/10.21105/jose.00044)

**We need your help!**

Journal of Open Source Education is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. 
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jose

**Comment by labarba** [comment]
https://twitter.com/JOSE_TheOJ/status/1115582355140378624

**Comment by moorepants** [comment]
Congrats @CameronDevine and thank you @chrisdembia and @gboeing!

**Comment by CameronDevine** [comment]
Thanks @labarba, @moorepants, @chrisdembia, and @gboeing for all your comments. I believe the review process has made some substantial improvements to the software.

**Comment by CameronDevine** [comment]
@moorepants, You asked about the benefits of Linear Graphs early in the review process. I forgot about your question until I was reviewing some notes today.

The main benefit of Linear Graphs is the resulting diagram is almost identical to an electrical circuit diagram. Since students often learn to read electrical circuit diagrams in physics, we can leverage this existing knowledge.

If you have any other questions, feel free to email me, camdev@uw.edu.

**Comment by labarba** [comment]
:loudspeaker:  New Reviewer Sign-up Form!
https://forms.gle/Rizd3TcHnQKhrbYY7
