### ISSUE TITLE
[PRE REVIEW]: Course Materials for Data Science in Practice

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#86]
**Submitting author:** @TomDonoghue (<a href="http://orcid.org/0000-0001-5911-0472">Thomas Donoghue</a>)
**Repository:** <a href="https://github.com/DataScienceInPractice/Site" target ="_blank">https://github.com/DataScienceInPractice/Site</a>
**Version:** 1.0
**Editor:** @magsol
**Reviewers:** @KiCh84, @krother

**Author instructions**

Thanks for submitting your paper to JOSE @TomDonoghue. **Currently, there isn't an JOSE editor assigned** to your paper.

@TomDonoghue if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Reference check summary:

OK DOIs

- 10.21105/jose.00032 is OK
- 10.5281/zenodo.2799972 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/jose-papers/blob/jose.00086/jose.00086/10.21105.jose.00086.pdf)

**Comment by labarba** [comment]
👋  @TomDonoghue  — I'm ready to look for an editor to handle review of your submission. The repository you provided here seems to hold just the paper and some additional info, however. We expect the repository of the complete learning materials, with the JOSE paper either in a folder in there, or if you prefer visible in a branch. Could you reorganize your submission in this manner and report the GitHub URL here?

At the end of review, and when the paper is accepted, we will ask you to make an archive of the full repository on Zenodo or a similar service, and the archive DOI will be linked in the paper and added in the metadata of the paper's Crossreff deposit.

**Comment by TomDonoghue** [comment]
Hey @labarba - thank you handling the submission! 

In terms of an editor, I wasn't sure about recommending a specific editor at submission (in terms of who is available in these times), but in terms of content, when I checked the listing, potentially @\juanklopper is one of the most related, by topic. 

In term of the repository, the project collects and makes public some materials for a university course, and the main "deliverable" is the website with all of the materials (https://datascienceinpractice.github.io/). I have now updated the repository so that the repository itself also includes the materials that are hosted. I have also updated the README to better describe the repository and it's contents. Hopefully this matches what is needed for the JOSE submission, and if any further updates are required, please let me know!

Please let us know if there is anything else we can do / assist with for the submission!

**Comment by TomDonoghue** [comment]
Hey @labarba - I just wanted to check in - is there anything more we can do to prepare the repository submission, and/or to help assign a handling editor? 

I'm not sure if we are supposed to directly link in editors, but I think potentially @\juanklopper is related to the topic, and/or @\magsol does related work (using Python for data analysis, etc).

**Comment by kyleniemeyer** [comment]
Hi @TomDonoghue, sorry for the extended delay here!

@juanklopper, are you able to take on this paper as editor?

**Comment by TomDonoghue** [comment]
Hey @kyleniemeyer - thanks for picking this up! It seems maybe @juanklopper isn't available? When I checked through, I think another related editor would be @\magsol (I'm not tagging directly in in case that is something that you should do).

**Comment by TomDonoghue** [comment]
Hey @kyleniemeyer - just wanted to follow up here. Is there anything we can do to help get this submission moving along?

**Comment by kyleniemeyer** [comment]
@TomDonoghue I will check on things outside of GitHub

**Comment by voytek** [comment]
What's the status of this?

**Comment by kyleniemeyer** [comment]
Hello @magsol, can you edit this submission for us? Thanks!

**Comment by TomDonoghue** [comment]
Pinging on this - it seems perhaps @magsol  is not available to handle the submission?

If not, @kyleniemeyer and/or @labarba - could you let you know if JOSE is operational and if you expect this submission to be processed / reviewed, and if so, when?

I understand things are slower during a pandemic - but we submitted this paper around July 1st - almost 5 months ago. There was not then (nor is there now) any indication at submission JOSE was not actively processing papers. If we had JOSE was not operational, we would not have spent time preparing this submission. Please let us know what is going on here, and if things are to remain paused - I would suggest at least mentioning this on the JOSE journal & submission page, so that potential submitters know the status.

**Comment by labarba** [comment]
Hi @TomDonoghue — It is I who became the bottleneck for JOSE, as the pandemic made all my service obligations too much to do them all. I was JupyterCon General Chair, and the pivot to an online event was a huge lift (it was held in October). I'm just beginning to dig from under the rubble of all that I'm behind on, and will start processing the several stalled JOSE submissions. Thank you for your patience.

**Comment by magsol** [comment]
Hi @TomDonoghue and @kyleniemeyer, so sorry I missed the earlier pings--I've been on paternity leave the last several weeks so quite a lot has fallen through the cracks. I'm still trying to push through a separate stalled JOSE submission, but if you can't find another editor, I can see about this one.

**Comment by TomDonoghue** [comment]
@labarba - thanks for getting back to us and the update. I understand there is a lot going on! Is there anything we can do to help move this paper along? 

In terms of assigning a managing editor, my original editor suggestions were @juanklopper and/or @magsol (thanks for answering - but I don't want to pull you in from paternity leave, if avoidable!). The submission is fairly broad (in terms of covering data science / scientific Python), so I imagine other editors would overlap a lot with it, in so far as they work within scientific python - so other possible editors might be @\moorepants or @\ianhawke, based on my understanding of the editor list.

**Comment by voytek** [comment]
Hey all, just popping back in to check on this...

**Comment by TomDonoghue** [comment]
Trying again.... @labarba and/or @kyleniemeyer - do you think it would be possible to get this going? We would still like to get this reviewed and potentially published in JOSE if possible. We still need a managing editor.

**Comment by voytek** [comment]
So it's been almost a year @labarba and @kyleniemeyer. It looks like other papers are getting reviewed—on similar topics. Can we move this forward, please?

**Comment by labarba** [comment]
@whedon invite @magsol as editor

**Comment by whedon** [comment]
@magsol has been invited to edit this submission.

**Comment by magsol** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @magsol

**Comment by magsol** [comment]
@TomDonoghue Welp, I'm back from paternity leave, so let's give this a go, shall we?

**Comment by TomDonoghue** [comment]
@magsol - sounds good, thanks for jumping on board! It's been a little while since I worked through the details of this paper, but everything should be in pretty good shape I think - the paper generates, and refers to a collection of online learning materials available one the website. 

The topic is pretty general data science (in Python) - do you need me to look through the JOSE reviewer list and recommend some potential reviewers?

**Comment by magsol** [comment]
@TomDonoghue I wouldn't say no! :) Thank you!

**Comment by TomDonoghue** [comment]
Hey @magsol: in terms of reviewers, I checked through the list of reviewers, checking through based on the intersection of Data Science + Python (+teaching and/or other relevant topics), and I find the following potential reviewers (non exhaustive list):
- Dr. Kristian Rother (krother)
- Sarah Masud (sara-02)
- Albert Y. Kim (rudeboybert)
- Giulio Valentino Dalla Riva (gvdr)
- Justin Bois (justinbois)
- Tania Allard (trallard)
- Brandon LeBeau (lebebr01)

Also, assuming it's okay to do so, in the next day or two, I'll do a sweep through the paper, and check if there are any minor updates to do (since it's been a while since I looked at this paper), and add in a reference to some other work we've done on teaching data science.

**Comment by magsol** [comment]
@whedon assign krother as reviewer

**Comment by whedon** [comment]
OK, krother is now a reviewer

**Comment by magsol** [comment]
@whedon add @KiCh84 as reviewer

**Comment by whedon** [comment]
OK, @KiCh84 is now a reviewer

**Comment by magsol** [comment]
@whedon remove krother as reviewer

**Comment by whedon** [comment]
OK, krother is no longer a reviewer

**Comment by magsol** [comment]
@whedon add @krother as reviewer

**Comment by whedon** [comment]
OK, @krother is now a reviewer

**Comment by magsol** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/openjournals/jose-reviews/issues/121.
