### ISSUE TITLE
[PRE REVIEW]: Importance and Capabilities of Modern Web Applications for Accessible Education: Demonstration of a Purpose-Built Application for Visualizing Geologic Data in 3D

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#98]
**Submitting author:** @jperryhouts (<a href="http://orcid.org/0000-0002-3652-6202">Jonathan Perry-Houts</a>)
**Repository:** <a href="https://github.com/jperryhouts/CRB-Explorer" target ="_blank">https://github.com/jperryhouts/CRB-Explorer</a>
**Version:** v1.0.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSE @jperryhouts. **Currently, there isn't an JOSE editor assigned** to your paper.

@jperryhouts if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.84  T=0.07 s (67.0 files/s, 17074.0 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JavaScript                       1             87             46            737
HTML                             1             13              1            242
TeX                              1              7              0             68
Markdown                         2             20              0             54
-------------------------------------------------------------------------------
SUM:                             5            127             47           1101
-------------------------------------------------------------------------------


Statistical information for the repository 'b6a44c61bd3241beac30eaa1' was
gathered on 2020/11/23.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jonathan Perry-Houts            33          1483            613          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jonathan Perry-Houts        870           58.7          1.3                5.29
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00098/jose.00098/10.21105.jose.00098.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00098/jose.00098/10.21105.jose.00098.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/jose.00070 is OK
- 10.21105/jose.00075 is OK
- 10.3133/ofr81797 is OK
- 10.3133/i1139 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by labarba** [comment]
hi @jperryhouts 👋  — in your paper, we're missing some discussion of "usage and recent experience of use in teaching and learning situations." See our documentation on [what the paper should contain.](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain)

**Comment by labarba** [comment]
hmm... I'm looking at your repository now. Is all the code you are submitting this ~700 loc of JavaScript? https://github.com/jperryhouts/CRB-Explorer/blob/master/visualizer.js
It seems fairly minor for a journal paper. Can you justify how the scope of this work merits publication, by itself?

**Comment by jperryhouts** [comment]
> hi @jperryhouts wave — in your paper, we're missing some discussion of "usage and recent experience of use in teaching and learning situations." See our documentation on [what the paper should contain.](https://openjournals.readthedocs.io/en/jose/submitting.html#what-should-my-paper-contain)

Hi @labarba. Thanks for taking the time to review our paper. Sorry I didn't catch that an example experience was necessary. Before I expand the paper, it's probably worth addressing the other point, as to whether this is fit for publication in JOSE at all.

> hmm... I'm looking at your repository now. Is all the code you are submitting this ~700 loc of JavaScript? https://github.com/jperryhouts/CRB-Explorer/blob/master/visualizer.js
> It seems fairly minor for a journal paper. Can you justify how the scope of this work merits publication, by itself?

Yes, one of the key takeaways\* from the paper is demonstrating the feasibility of creating customized interactive educational tools which would traditionally either be infeasible to produce, or would require students learn more complex generalized software like Paraview in order to even begin interacting with the lesson. If anything I would have liked to make the code shorter, but the paper isn't intended to explain *how* to make such a tool as much as it is to demonstrate what's possible for custom educational software.

With that said, do you think this is worth completing with details on an educational experience, or is it not fit for JOSE regardless?

\* The second takeaway is that web browsers provide a universal platform for software distribution that reduces the technical overhead required to access these tools, thus the use of Javascript.

**Comment by labarba** [comment]
What you're describing sounds like a proof of concept. A JOSE paper does not need to explain how to make a tool like you describe, but it does have to present a finished product (either learning module or technology for teaching) that has a clear educational use and can be adopted by others in their teaching.

**Comment by jperryhouts** [comment]
I've been discussing this with my coauthor and it sounds like there's no obvious way to make this fit what JOSE is looking for. Just to be sure I'm understanding you correctly, it sounds like there are two issues here. One is that this paper doesn't describe an experience using the software for teaching, and the other is that this paper focuses on describing a type of software rather than focusing as much on this specific piece of code.

The first of those two would be a straightforward revision, but the second one may just be a mismatch with JOSE's scope that is not possible to reconcile. I'm a little surprised that there isn't room in JOSE for that type of material though, since it seems compatible with all of the aims of the journal and would have a much wider audience than were it focused only on one particular tool.

It looks like I don't have access to close this github issue, but you're welcome to close it whenever. Thank you for taking the time to consider our manuscript.

-Jonathan

**Comment by labarba** [comment]
JOSE was founded in the likeness of JOSS, the Journal of Open Source Software. JOSS provides publication credit for research software, recognizing that more and more researchers spend a big chunk of their time writing specialist code, and this is not recognized in traditional publication venues. There's a bar to pass in JOSS, which leaves wrapper code, utility packages, and interfaces out of scope. The software has to contain substantial scholarly content.

Similarly, in JOSE we look to provide publication credit for substantial work developing software in support of the teaching mission (e.g., auto-graders for computational notebooks, see [nbgrader](https://jose.theoj.org/papers/10.21105/jose.00032)), or developing learning materials that use computing integrated in the curriculum. Those are the two [submission types](https://openjournals.readthedocs.io/en/jose/submitting.html#the-two-submission-types).

My first assessment is that your submission is _out of scope_, and I can flag a few issues: 1) its size: at 700 loc of JS, it doesn't seem like a substantial enough piece of work to merit a journal article (we aim for JOSE articles to "count" the same as a research article); 2) its usage: it is not built for reuse, but rather as a prototype; 3) its specificity: "An interactive web tool for visualizing contacts between geologic units in the Columbia River Basalt Group" seems very specific, unless it came attached to both learning content and context.

**Comment by jperryhouts** [comment]
I understand and respect those points --- just a bit disappointed. Sorry if I came across as confrontational about it. That was not my intent. I sincerely appreciate your time with this.

Have a good rest of your term!
